### ISSUE TITLE
v1.0 Todo List

### ISSUE THREAD

**Issue by nomi-san** [nomi-san/parsec-vdd#71]
#### Features

- [x] Multilingual support
- [x] CLI support (#13)
- [x] Upgrade to .Net Framework 4.7.2
- [x] Restore added displays (#70)
- [ ] Power events support (513707336799af2a53a0895d22c388d612a73008)
- [x] Update checker
- [x] Choose parent GPU (#46)
- [ ] New threading model (#58)
- [x] Use WinForms tray menu (#28)
- [ ] Allow to run app with broken driver/not installed (#27)
- [ ] v0.41 driver install for unsupported Windows (#27)

#### Bugs

- [ ] #40 
- [ ] Incorrect high DPI screenshot (#12)

#### Add your features request below and before this December.

**Comment by ataraxia-admail** [comment]
If i understand correctly, restore added displays means it is able to automatically add display upon our PC startup with the run on startup feature right?

**Comment by nomi-san** [comment]
@ataraxia-admail This feature is currently able to add the recently added displays from your previous session when you reopen the app. With run on startup, it will do things like you said. And with power events support, it should work with sleep/hibernate without breaking the driver.

**Comment by soi8391** [comment]
@nomi-san Is it possible to add a virtual screen that Windows recognizes as having touch functionality? This might be helpful for streaming certain games that support touch features. Thank you for your response.

**Comment by nomi-san** [comment]
@soi8391 This feature is out of scope. You should turn your Windows into touch/tablet mode. For remote desktop, use an app that supports full of translation touch gestures, such as AnyDesk and SteamLink.

**Comment by UnCLAS-Prommer** [comment]
> @nomi-san Is it possible to add a virtual screen that Windows recognizes as having touch functionality? This might be helpful for streaming certain games that support touch features. Thank you for your response.

What's the streaming client are you using? I use Sunshine and a modified version of moonlight and it support touch gestures. Touching support is added by the modified version of moonlight, not Parsec VDD itself.
[Modified version of moonlight](https://github.com/Axixi2233/moonlight-android)

**Comment by soi8391** [comment]
@UnCLAS-Prommer Thank you for your reply. I used the client you recommended, but I found that the game I’m playing only automatically switches to the touch interface when the touchscreen is active. Therefore, it seems that this client does not solve the issue.

**Comment by trekshcool** [comment]
I am trying to use this with moonlight and sunshine but am running into issues, when moonlight tries to connect VDD seems to not make a virtual display. How have you guys been able to get this working with moonlight or is that not possible?

**Comment by JonSnow88** [comment]
> [@ataraxia-admail](https://github.com/ataraxia-admail) This feature is currently able to add the recently added displays from your previous session when you reopen the app. With run on startup, it will do things like you said. And with power events support, it should work with sleep/hibernate without breaking the driver.

This does not work with the 1.0.2 build from my testing
